name: Build and Deploy Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      appVersion:
        description: "Application version (image tag)"
        required: true

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Qcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker to GCR
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build Docker Image
        run: |
          docker build -t us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-world:${{ github.event.inputs.appVersion }} .

      - name: Push Docker Image
        run: |
          docker push us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-world:${{ github.event.inputs.appVersion }}

      - name: Update Helm Values
        run: |
          sed -i "s/tag:.*/tag: \"${{ github.event.inputs.appVersion }}\"/" charts/hello-world/values.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add charts/hello-world/values.yaml
          git commit -m "Update image tag to ${{ github.event.inputs.appVersion }}"
          git push origin main
